### ISSUE TITLE
Games Running Insanely Slow

### ISSUE THREAD

**Issue by Shrimbop** [firelad97/PROM-PCSX2-Running-on-Mac#10]
So I finally got PROM working after installing the forked version to get around the C++ runtime errors. However, almost every game I play runs at around 35% speed and is basically unplayable. It's entirely possible my Mac just sucks and can't play this, which if that's the case, that's fine, but wondering if anyone has any tips to improve performance?

My computer is a Macbook Pro from 2015, 2.7 GHZ Intel Core i5, Intel Iris Graphics 6100 1536. I'm not super savvy, so if this just can't run stuff, I guess that's just what it is.

**Comment by sjaykub** [comment]
@Shrimbop I recommend https://www.game-debate.com/games/index.php?g_id=6219&software=PCSX2, put your spec and game you want to play, it tells you which spec you are lacking. But It is not done by experts I guess, so it is just a suggestion.

You are lucky, I still am stuck on c ++ error and I cant install pcsx2 to prom from the forked version.

**Comment by sjaykub** [comment]
@Shrimbop I also recommend https://pcsx2.net/ go to compatibility section and type your game to see if it works well with the emulator.

**Comment by Shrimbop** [comment]
Awesome, thanks for the tips guys!

**Comment by sjaykub** [comment]
@Shrimbop , but from eyeballing I think your spec is ok for normal games unless you play some crazy high spec games. Both above will at least help if your spec is the problem.

**Comment by Shrimbop** [comment]
I was trying to play Tales of the Abyss if we're getting specific - it runs fine in hardware mode with a bunch of graphical issues and occasional slowdown, and then if i switch to software it runs at about 30% but the graphical issues go away. Digital Devil Saga runs at a crawl though.

**Comment by sjaykub** [comment]
Those two games are playable under PCSX2, so thats a good start...

**Comment by Shrimbop** [comment]
I can get Abyss to about 90% for the most part, which isn't bad, just a ton of graphical bugs but it's definitely playable. DDS is at about 30% though, it's weird. Guess I'll just learn to live with it. Thanks!

**Comment by sjaykub** [comment]
@Shrimbop try pscx2 1.4.0 version. It works for me but I play shitty game fifa 05

**Comment by Shrimbop** [comment]
Thanks! I've been using 1.4.0. I assume 1.6 would improve things (maybe?) but I can't get it to work.

**Comment by sjaykub** [comment]
So can't I, it sucks that after days of trying, game goes so slow with glitchy graphic, but I guess it is on my spec SMH.

**Comment by firelad97** [comment]
Apologies - PROM is supposed to be experimental and in testing stages. Not everything work yet. However, your computer specs can be another issue. PCSX2 itself runs better if you have an AMD card or M1 chip.

For time being, I recommend try Boot Camp (dual booting) or [this one](https://forums.pcsx2.net/Thread-Native-Mac-Testing-Build) that might help. Closing. Please continue to comment if you have any more questions.
