### ISSUE TITLE
880MB wrapper? for a 7MB installer?

### ISSUE THREAD

**Issue by macmeister1967** [firelad97/PROM-PCSX2-Running-on-Mac#11]
Surely there must be a way to shrink this down somewhat?!

In this age of smaller SSD boot drives, it doesn't take long to fill up with 880MB wrappers... 👎

**Comment by firelad97** [comment]
It is 880 MB because of the dependencies that PCSX2 requires, and without them PCSX2 won't run outside of Windows. Those dependencies are mostly already pre-installed or you installed before installing PCSX2 on Windows. Closing this because it is not relevant.
