### ISSUE TITLE
Winsekin error: No new executables found!

### ISSUE THREAD

**Issue by iwbiz** [firelad97/PROM-PCSX2-Running-on-Mac#2]
Getting the following dialog:
<img width="454" alt="Screenshot 2020-06-02 at 21 26 15" src="https://user-images.githubusercontent.com/28648479/83561253-d1264b00-a517-11ea-8232-ec2fd1766c30.png">

Catalina 10.15.3
PROM v1.1.0 beta
pcsx2 1.6.0 stable

I can not choose the install location. Open PROM (Wineskin) I click on Install Software, then click "Choose Setup Executable" then select the pcsx2 exe file and it starts installing. That's it.

**Comment by firelad97** [comment]
From what the error is saying, you mustn't change the directory when installing PCSX2. Leave it to Program Files and it will work. If error continues even after successfully installing PCSX2, then do the following:
- Right click PROM and click Show Package Contents.
- Go to drive_c/Program Files (x86)/PCSX2
- Check if it has "pcsx2.exe"
- Reopen PROM and go to Advanced > Change executable file
- Close and open PROM again  
-  Otherwise, please report back

**Comment by iwbiz** [comment]
Unfurtunately there is no PCSX2 folder installed in drive_c/Program Files (x86).
The error above pop's up in the middle of the installation process, and then doesn't do anything more.

**Comment by tunghoang285** [comment]
So I downloaded the PCSX2 1.6.0 and put it in the drive_c/Program Files (x86) in the PROM packaged content. I opened PROM.app after that but nothing happens

**Comment by firelad97** [comment]
@iweurman - where is your PROM.app located? depending on where you put it, there could be issues. try dragging it to desktop and try again. Let me know if it fixes for you.

@tunghoang285 - that is an seperate issue, please make a new issue for that, thank you. Also, you're supposed not to put the installer file inside PROM.app, you're supposed to install it as I had already explained on the wiki.

**Comment by iwbiz** [comment]
> @iweurman - where is your PROM.app located? depending on where you put it, there could be issues. try dragging it to desktop and try again. Let me know if it fixes for you.

Hmm still same error as described above when moved the PROM.app to desktop.
FYI: I have not touched any configurations. Just the initial PROM installation.

Does this have to do with the beta? because I also need to do the step which is described in other thread (with the sudo xattr -r -d etc...) otherwise PROM beta does not open for me.

**Comment by laggamer** [comment]
I also got that image in first post.  I had to do xattr -r -d thing to have P.R.O.M. open.  When trying to install pcsx2 1.6.0 standalone installer by clicking install software and choosing setup executable, and while not touching any configurations, I got error message that no windows program is configured to open this type of file 
![Screen Shot 2020-06-04 at 9 56 05 PM](https://user-images.githubusercontent.com/66453218/83832144-97d41380-a6ae-11ea-8cc2-9984b5d54dc2.jpeg)
and then that no executable found message.
![Screen Shot 2020-06-04 at 9 52 19 PM](https://user-images.githubusercontent.com/66453218/83832288-e84b7100-a6ae-11ea-879b-7f297d77dd79.jpeg)

MacBook Air Catalina 10.15.5

**Comment by jameswfang** [comment]
@iweurman I ran into the same error but did the following:

- Download the PCSX2 1.6.0 binary
- Unzip the PCSX2 1.6.0 folder
- Rename the folder to PCSX2
- Right click PROM and click Show Package Contents
- Move the PCSX2 folder to drive_c/Program Files (x86)/PCSX2
- Reopen PROM and go to Advanced > Change executable file to drive_c/Program Files (x86)/PCSX2/pcsx2.exe

That did the job for me and I was able to launch PCSX2.

My new problem, however, is I'm getting a C++ Runtime Error when I load an .iso and boot (Full) or boot (Fast).
![image](https://user-images.githubusercontent.com/24444212/83846875-256c2f00-a6c0-11ea-8cd5-d7e0bb80a099.png)

Note, it's called out in Gcenx issues: https://github.com/Gcenx/WineskinServer/issues/26

The thread suggests going back to PCSX2 1.4.0 and using DirectX 9... but I haven't tried that (and seems like that defeats the purpose)

**Comment by firelad97** [comment]
Woah, I wasn't really expecting this. The weird thing is, 1.6.0 works flawlessly on my computer. I'll have to figure this out why this is happening.

But otherwise, I'll have to suggest the other solution: use BootCamp to install Windows for dual booting, and from there you can use PCSX2 without any issues. Unfortunately, I can't help much until I am able to figure this out.

**Comment by iweurman** [comment]
> @iweurman I ran into the same error but did the following...

Oh this worked perfect, it opens perfectly now! Lets see if I can run somthing.
Thanks a lot !

**Comment by iwbiz** [comment]
> @iweurman I ran into the same error but did the following:
> 
> * Download the PCSX2 1.6.0 binary
> * Unzip the PCSX2 1.6.0 folder
> * Rename the folder to PCSX2
> * Right click PROM and click Show Package Contents
> * Move the PCSX2 folder to drive_c/Program Files (x86)/PCSX2
> * Reopen PROM and go to Advanced > Change executable file to drive_c/Program Files (x86)/PCSX2/pcsx2.exe
> 
> That did the job for me and I was able to launch PCSX2.
> 
> My new problem, however, is I'm getting a C++ Runtime Error when I load an .iso and boot (Full) or boot (Fast).
> ![image](https://user-images.githubusercontent.com/24444212/83846875-256c2f00-a6c0-11ea-8cd5-d7e0bb80a099.png)
> 
> Note, it's called out in Gcenx issues: [Gcenx/WineskinServer#26](https://github.com/Gcenx/WineskinServer/issues/26)
> 
> The thread suggests going back to PCSX2 1.4.0 and using DirectX 9... but I haven't tried that (and seems like that defeats the purpose)

Thanks, this worked also! Here my proof: 
![image](https://user-images.githubusercontent.com/28648479/83890857-a07b2700-a74c-11ea-87b9-dabd419500b1.png)

@jameswfang This is nice, also make sure Windows EXE path is exactly:
"C:\Program Files (x86)\PCSX2\pcsx2.exe"

@firelad97 This might be a good solution, instead of using the .exe installer, just download the binary zip and unpack it inside the package contents --> drive_c/Program Files (x86)/PCSX2/pcsx2.exe.
Then change the path to: "C:\Program Files(x86)\PCSX2\pcsx2.exe"

I will update on further findings. Gonna try to run some ISO's lets see what happens...

UPDATE
Stumbled upon the same error which @jameswfang also had.
Maybe it has to do becaues we're using the binary zip files.

**Comment by iweurman** [comment]
Stumbed on the following error, not sure what it means.
I'm running Need for speed underground ISO, but it also happens with other ISO's:

![image](https://user-images.githubusercontent.com/28648479/83897661-2780cd00-a756-11ea-9edb-d7f72bd1e5f6.png)

**Comment by firelad97** [comment]
@iweurman That solution is not suggested. There are a few reasons to that:
- The binary version is a portable version of PCSX2 (also included in 1.6.0 installer)
- You will have access PROM.app every time you need to back up files or to move files around (such as bios and memory cards)
- It was not designed in mind for PROM

**Comment by jameswfang** [comment]
There's an alternative workaround I found:

- Download the PCSX2 1.6.0 installer (pcsx2-1.6.0-setup.exe)
- Right click on PROM.app and show package content. Move the installer to C:\Program Files(x86)\
- Open PROM.app, which should open up Wineskin (if already installed, right click and show package contents, then double click Wineskin)
- Under Advanced > Change executable file to "C:\Program Files (x86)\pcsx2-1.6.0-setup.exe"
- Click "Test Run", it will run the installer
- Follow the original instructions (e.g. Uncheck add shortcuts, "Run" post install)
- Under Advanced > Change the executable file back to "C:\Program Files (x86)\PCSX2\pcsx2.exe"

**Comment by jameswfang** [comment]
@firelad97 On the second issue, the PCSX2 forum highlights this workaround on Page 6:

> I'm using DX9 plugin from 1.4 version in 1.6 - for geting hardware directX renderer

https://forums.pcsx2.net/Thread-macOS-P-R-O-M-PCSX2-Running-on-Mac-64-bit-Now-runs-on-Catalina?page=6

I'm not quite sure how to do that, but sounds like that a suggestion for a workaround. If anyone can get it to work and is willing to post step-by-step instructions, would be appreciated, thanks!

**Comment by iwbiz** [comment]
> @firelad97 On the second issue, the PCSX2 forum highlights this workaround on Page 6:
> 
> > I'm using DX9 plugin from 1.4 version in 1.6 - for geting hardware directX renderer
> 
> https://forums.pcsx2.net/Thread-macOS-P-R-O-M-PCSX2-Running-on-Mac-64-bit-Now-runs-on-Catalina?page=6
> 
> I'm not quite sure how to do that, but sounds like that a suggestion for a workaround. If anyone can get it to work and is willing to post step-by-step instructions, would be appreciated, thanks!

Hey @jameswfang there is a Plugins folder if you open the package contents, drive_c\Program Files(x86)\PCSX2\Plugins and a list of .dll files.
Maybe if unzip the downloaded plugin and place the GSdx9.dll in there? ( just suggestion ) not sure if it works.

**Comment by iwbiz** [comment]
> There's an alternative workaround I found:
> 
> * Download the PCSX2 1.6.0 installer (pcsx2-1.6.0-setup.exe)
> * Right click on PROM.app and show package content. Move the installer to C:\Program Files(x86)\
> * Open PROM.app, which should open up Wineskin (if already installed, right click and show package contents, then double click Wineskin)
> * Under Advanced > Change executable file to "C:\Program Files (x86)\pcsx2-1.6.0-setup.exe"
> * Click "Test Run", it will run the installer
> * Follow the original instructions (e.g. Uncheck add shortcuts, "Run" post install)
> * Under Advanced > Change the executable file back to "C:\Program Files(x86)\PCSX2\pcsx2.exe"


@jameswfang Confirmed this worked as well for me! 
Only make sure path is correct: "C:\Program Files (x86)\PCSX2\pcsx2.exe".
You miss a space between Files and (x86).

cc @firelad97
I don't think it matters where we place the installer exe file, but maybe it works to put it inside the PROM package contents?

**Comment by laggamer** [comment]
I can confirm that placing the installer in the wrapper in the section of program files x86 then have wineskin executable file to the installer works.  After finished installing by following instructions, I changed executable file to "C:\Program Files (x86)\PCSX2\pcsx2.exe".  PCSX2 does open with all of that.

**Comment by wh111msy** [comment]
tried your suggestion @iweurman , got to 'test run' step, wine quit unexpectedly and now PROM wont open for me at all...trying it all over again now, will update.

Attempt #2, dialog window pops up saying "success!", log of test run reads
"i386_set_ldt: Operation not permitted
wine: failed to initialize: failed to set the LDT entry for 32-bit code segment"

any help?

**Comment by iwbiz** [comment]
> tried your suggestion @iweurman , got to 'test run' step, wine quit unexpectedly and now PROM wont open for me at all...trying it all over again now, will update.
> 
> Attempt #2, dialog window pops up saying "success!", log of test run reads
> "i386_set_ldt: Operation not permitted
> wine: failed to initialize: failed to set the LDT entry for 32-bit code segment"
> 
> any help?

Which versions are you using of pcsx2, prom and your mac?

**Comment by wh111msy** [comment]
> Which versions are you using of pcsx2, prom and your mac?

Using pcx2-1.6.0, using prom as downloaded from this github, and running catalina 10.15.2

**Comment by Gcenx** [comment]
This repository is missing additional instructions that are currently required to launch `wine32on64` These are listed on the README of my repository.

For macOS Catalina 10.15.3 > 10.15.0 SIP need to be disabled to allow access to `i386_set_ldt`, macOS Catalina 10.15.4 and greater don’t require SIP to be disabled however to avoid some issue you need to run the following command from recovery mode `nvram boot-args=“no32exec=0”` this will resolve these `There is no windows executable configured to open this type of file`

**Comment by michael-ziedalski** [comment]
Just wanted to leave my (obvious) 2 cents here, but the solution of having to move the installer `.exe` to a folder within the C: Drive to allow installation (which worked for me, thankfully) is a bit confounded.

Thanks for the useful comments in this thread.

**Comment by Gcenx** [comment]
@michael-ziedalski the simple solution to resolve the issue is to disable SIP as that’s what’s blocking access to your user directories. (Also means it can work on lower Catalina patch versions)

As most don’t want to have SIP disabled the alternative would be using the pre-releases I’ve provided that resolved some long standing bugs within Wineskins BundleID generation, this along with the removal of bash wrappers then allows the wrapper to request permissions as there required

Edit;\
Descended to just push the wrapper that’s been worked on for months now to everyone who uses my provided Winery

**Comment by michael-ziedalski** [comment]
Hi, Gcenx. For reference, it might not be only SIP-related, as I just confirmed on my Mac that SIP is currently disabled,
<img width="388" alt="Screen Shot 2020-09-07 at 12 54 30 AM" src="https://user-images.githubusercontent.com/43689829/92349734-f2fa1580-f0a4-11ea-9025-9b054d4f6fe8.png">

**Comment by Gcenx** [comment]
@michael-ziedalski I've only seen this happen when the users tccd database was corrupted.

The new master wrapper when added to “Full Disk Access” is able to access any and all directories without issue.

**Comment by Gcenx** [comment]
@michael-ziedalski here’s a desktop recording of me using my latest master wrapper and it requesting permissions (SIP is enabled on my system) this was done after running tccd-reset script.

https://youtu.be/Klzn6MhaKtw

At the end I show attempting to install audacity that had the quarantine flag as it was downloaded using Chrome
